name: Keep Replit Alive

on:
  schedule:
    - cron: '*/1 * * * *'  # Ejecuta cada minuto

jobs:
  ping-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to Replit
        run: curl -s https://replit.com/@landerteran663/Osu-rate-changer-online-v131-F.repl.co  # Aquí va la URL pública
